# Generated by Django 3.2 on 2022-04-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Four Wheeler', 'Four Wheeler'), ('Two Wheeler', 'Two Wheeler')], max_length=200)),
                ('vehicle_company', models.CharField(blank=True, choices=[('Tata', 'Tata'), ('MG', 'MG'), ('Mahindra', 'Mahindra'), ('Porsche', 'Porsche'), ('Nissan', 'Nissan'), ('Jaguar', 'Jaguar'), ('Mini Cooper', 'Mini Cooper'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Mercedes', 'Mercedes'), ('Byd', 'Byd')], max_length=200, null=True)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_connector', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
