# Generated by Django 3.2 on 2022-04-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220413_1211'),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
                ('vehicles', models.ManyToManyField(to='garage.Vehicle')),
            ],
        ),
    ]
